"""add lock_tx_id to generations

Revision ID: a1b2c3d4e5f6
Revises: 78a9e8e145e5
Create Date: 2026-04-17 21:24:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '78a9e8e145e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('lock_tx_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_generations_lock_tx_id', 'generations', 'token_transactions', ['lock_tx_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_generations_lock_tx_id', 'generations', type_='foreignkey')
    op.drop_column('generations', 'lock_tx_id')
    # ### end Alembic commands ###
